### ISSUE TITLE
Weird behavior on flashing ESP32

### ISSUE THREAD

**Issue by dz0ny** [pkendall64/elrs-web-flasher#6]
https://user-images.githubusercontent.com/239513/180862629-b90d91c6-d66e-47ce-9077-b63e4ec34421.mov

https://user-images.githubusercontent.com/239513/180862678-f4864e2a-a850-4050-a6fc-83d95158d15e.mov

This is happymodel tx, otherwise flashes fine with pio, esptool. I've also tested with esp-web-tools which also uses esptool-js https://github.com/esphome/esp-web-tools/blob/main/src/flash.ts and it works fine.

**Comment by pkendall64** [comment]
I've fixed the issue in master. The main problem was the resetting back to the start which I traced back to commit that changed the flash and connect button from input type button to button! Perhaps you have some insight as to what would be different there?

**Comment by dz0ny** [comment]
Got it nicely working with this patch https://github.com/pkendall64/elrs-web-flasher/pull/7/files#diff-78f2697f19f34a969e13f9ba6c41e427699491cb09697890209bf4d3cb522d40R13, looks like the autobaud is the issue.

**Comment by dz0ny** [comment]
Fixed in linked PR.
