### ISSUE TITLE
After flashing, UI loses the connection state

### ISSUE THREAD

**Issue by dz0ny** [pkendall64/elrs-web-flasher#8]
When one flashes the image, then goes back to start of wizard and then comes progresses to the last flash step, the Serial will be still connected but the button will say it's not.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/239513/181098867-fee5ca95-8581-4887-8dea-1c96c8dd8555.png">

1. I think navigating while flashing should not be allowed
2. After moving to first step and not flashing serial connection should be closed.

**Comment by pkendall64** [comment]
Yes, agreed, there are a bunch of cleanups, UX things I need to do.

**Comment by pkendall64** [comment]
I fixed this today, as well as a ton of other niceties in the UI.
Could you test and close if you're satisfied.
Open other tickets too if you find anything of note.

**Comment by dz0ny** [comment]
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/239513/181550104-f52820e7-ddaa-4dd8-90f7-846a6bb6a692.png"> is a biit too much. I would only show it if you click on a button for autodiscovery (button can be disabled but then you show for example question mark and only then show notice on click).

**Comment by pkendall64** [comment]
Fair call, I've re-developed that part and done some other UX cleanup along the way.
